M48
; DRILL file {KiCad 7.0.8-7.0.8~ubuntu23.04.1} date Tue 03 Oct 2023 08:57:53 PM +04
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-03T20:57:53+04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8-7.0.8~ubuntu23.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X5.05Y-3.025
X6.05Y-3.025
T0
M30
